// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillMatrix.Data;

#nullable disable

namespace SkillMatrix.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220331105250_IN")]
    partial class IN
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SkillMatrix.Model.BehaviourDrivenDevelopment", b =>
                {
                    b.Property<int>("BehaviourDrivenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BehaviourDrivenId"), 1L, 1);

                    b.Property<int>("Cucumber")
                        .HasColumnType("int");

                    b.Property<int>("Maven")
                        .HasColumnType("int");

                    b.Property<int>("UserApproach")
                        .HasColumnType("int");

                    b.HasKey("BehaviourDrivenId");

                    b.ToTable("BehaviourDrivenDevelopments");
                });

            modelBuilder.Entity("SkillMatrix.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportingManager")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SkillMatrix.Model.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SkillMatrix.Model.TestDrivenDevelopment", b =>
                {
                    b.Property<int>("TestDrivenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestDrivenId"), 1L, 1);

                    b.Property<int>("AdaptabilityFlexibility")
                        .HasColumnType("int");

                    b.Property<int>("CriticalAnalytical")
                        .HasColumnType("int");

                    b.Property<int>("CustomerFocus")
                        .HasColumnType("int");

                    b.Property<int>("DemonstratesTeamwork")
                        .HasColumnType("int");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<int>("InterpersonalSkills")
                        .HasColumnType("int");

                    b.Property<int>("LeadershipSkills")
                        .HasColumnType("int");

                    b.Property<int>("Management")
                        .HasColumnType("int");

                    b.Property<int>("NegotiationSkills")
                        .HasColumnType("int");

                    b.Property<int>("OralCommunication")
                        .HasColumnType("int");

                    b.Property<int>("PlanningOrganizing")
                        .HasColumnType("int");

                    b.Property<int>("PresentationSkills")
                        .HasColumnType("int");

                    b.Property<int>("ProblemSolvingSkills")
                        .HasColumnType("int");

                    b.Property<int>("ProcessConformance")
                        .HasColumnType("int");

                    b.Property<int>("TakesInitiative")
                        .HasColumnType("int");

                    b.Property<int>("WrittenCommunication")
                        .HasColumnType("int");

                    b.HasKey("TestDrivenId");

                    b.ToTable("TestDrivenDevelopments");
                });

            modelBuilder.Entity("SkillMatrix.Model.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("RoleLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
